### ISSUE TITLE
Random lockup after repeated data acquisition with digitizer

### ISSUE THREAD

**Issue by umute97** [SengerM/CAENpy#4]
Hello Matias,
first of all, thank you very much for this nice library. I'm using a DT5742 16-channel digitizer and want to do TCT measurements with it (I've checked out your blog so I know you did the same!). Unfortunately, I've been having an issue with this and was hoping, you could help me with it:

# Setup
Forced to use python3.7 with the measurement software I'm using at the moment, I'm afraid...
DT5742 hooked up to FNL analog readout board, reading out all 16 channels.
Following settings:
```yaml
digitizer:
    device: DT5742
    save_path: /home/readout/tct-waveforms
    sampling_frequency: 5000
    max_num_events_BLT: 1
    record_len: 1024
    acquisition_mode: sw_controlled
    ext_trigger: acquisition only
    fast_trigger: True
    fast_trigger_dig: True
    en_channels:
      - True
      - True
    post_trigger_size: 90 # in percent
    trigger_dc_offset: 54500
    trigger_th: 40000
```
The readout itself works pretty well and I was able to record sensible scans.
I make a 2D scan of my sensor with 15 triggers per data point. My code for the acquisition of one point:
```python
def read_and_save_events(self, max_num_events: int = 1):
        """Reads a specified number of events from the digitizer.

        Arguments
        ---------
        max_num_events: int, default 1
            Number of events to read.

        Returns
        -------
        nevts: int
            Number of events read.
        """
        nevts: int = 0
        data = []
        retries = 0
        while retries < MAX_RETRIES:
            retries += 1
            try:
                with self.device:
                    self.log.info("Reading %d events...", max_num_events)
                    while nevts < max_num_events:
                        time.sleep(0.05)
                        waveforms = self.get_waveforms()
                        current_nevts = len(waveforms)
                        nevts += current_nevts
                        data += waveforms
                        self.log.info(
                            "Read %d out of %d events...", nevts, max_num_events
                        )
                    data = self.get_waveforms()
                break
            except RuntimeError:
                self.log.error("Encountered error during read. Retrying...")
                self.hard_reset(self._device_id)
                self.close()
                self.device = CAEN_DT5742_Digitizer(self._device_id)
                self.init()
                time.sleep(RETRY_TIMEOUT)
        else:
            self.log.error("Too many retries, aborting read...")
        
        # Handle the data further below
        ...
```
# Issue
If I let the scan run for some time, after a random time, my measurement software locks up with one CPU core drawing 100%.

# Possible causes
I profiled with `py-spy` to get some more info:
![image](https://github.com/SengerM/CAENpy/assets/22895787/d9adb72a-8b05-45f2-9fe0-1b4ca40528c6)

It seems like the `_GetNumEvents` function is the culprit here. This is surprising to me, since this function is basically just a wrapper for the c-library call...

Do you have any suggestions?
